id: nodepool
title: Kubernetes Engine Node Pool
titlePlural: Kubernetes Engine Node Pools
category: Container
overviewShort: A node pool is a group of nodes within a cluster that all have the same configuration.
overview: |
 A node pool is a group of nodes within a cluster that all have the same
 configuration.
readme: |
 A node pool is a group of nodes within a cluster that all have the same
 configuration. Node pools use a NodeConfig specification. Each node in the pool
 has a Kubernetes node label, cloud.google.com/gke-nodepool, which has the node
 pool's name as its value. A node pool can contain only a single node or many
 nodes.

 When you create a cluster, the number and type of nodes that you specify
 becomes the default node pool. Then, you can add additional custom node pools
 of different sizes and types to your cluster. All nodes in any given node pool
 are identical to one another.

 For example, you might create a node pool in your cluster with local SSDs, a
 minimum CPU platform, preemptible VMs, a specific node image, larger instance
 sizes, or different machine types. Custom node pools are useful when you need
 to schedule Pods that require more resources than others, such as more memory
 or more local disk space. If you need more control of where Pods are scheduled,
 you can use node taints.

 You cannot configure a single node in a node pool; any configuration changes
 affect all nodes in the node pool.

 By default, all new node pools run the latest stable version of Kubernetes.
 Existing node pools can be manually upgraded or automatically upgraded. You can
 also run multiple Kubernetes node versions on each node pool in your cluster,
 update each node pool independently, and target different node pools for
 specific deployments.

 ## Learn More

 This content is from the [GCP documentation](https://cloud.google.com/kubernetes-engine/docs/concepts/node-pools).
