---
apiVersion: compute.gcp.crossplane.io/v1beta1
kind: Network
metadata:
  name: example-gke
spec:
  forProvider:
    autoCreateSubnetworks: false
    routingConfig:
      routingMode: REGIONAL
  reclaimPolicy: Delete
  providerRef:
    name: example
---
apiVersion: compute.gcp.crossplane.io/v1beta1
kind: Subnetwork
metadata:
  name: example-gke
spec:
  forProvider:
    region: us-central1
    ipCidrRange: "192.168.0.0/24"
    privateIpGoogleAccess: true
    secondaryIpRanges:
      - rangeName: pods
        ipCidrRange: 10.128.0.0/20
      - rangeName: services
        ipCidrRange: 172.16.0.0/16
    networkRef:
      name: example-gke
  reclaimPolicy: Delete
  providerRef:
    name: example
