---
apiVersion: container.gcp.crossplane.io/v1beta1
kind: GKECluster
metadata:
  name: negztest
spec:
  forProvider:
    location: us-central1 # indicates regional cluster
    networkRef:
      name: example-gke
    subnetworkRef:
      name: example-gke
    ipAllocationPolicy:
      useIpAliases: true
      clusterSecondaryRangeName: pods
      servicesSecondaryRangeName: services
  writeConnectionSecretToRef:
    namespace: crossplane-system
    name: negztest
  providerRef:
    name: example
  reclaimPolicy: Delete