id: bucketclass
title: BucketClass
titlePlural: BucketClasses
category: Storage
overviewShort: "A BucketClass is a non-portable resource class. It defines the desired spec of resource claims that use it to dynamically provision a managed resource."
overview: |
 "A BucketClass is a non-portable resource class. It defines the desired spec of resource claims that use it to dynamically provision a managed resource."
readme: |
 Full documentation can be found in the Crossplane [API Reference docs](https://doc.crds.dev/github.com/crossplane/provider-nop/storage.gcp.crossplane.io_bucketclasses.yaml).
