---
apiVersion: storage.gcp.crossplane.io/v1alpha3
kind: BucketClass
metadata:
  name: gcsbucket-standard
  labels:
    example: "true"
specTemplate:
  writeConnectionSecretsToNamespace: crossplane-system
  location: US
  storageClass: MULTI_REGIONAL
  providerRef:
    name: example
  reclaimPolicy: Delete
