---
apiVersion: iam.gcp.crossplane.io/v1alpha1
kind: ServiceAccount
metadata:
  name: perfect-test-sa
spec:
  properties:
  forProvider:
    displayName: "a beautiful service account"
    description: "perfection"
  reclaimPolicy: Delete
  providerRef:
    name: gcp-provider
