---
apiVersion: packages.crossplane.io/v1alpha1
kind: ClusterPackageInstall
metadata:
  name: provider-nop
  namespace: crossplane-system
spec:
  source: localhost:5000
  package: "crossplane/provider-nop"
