id: cloudsqlinstanceclass
title: CloudsqlInstanceClass
titlePlural: CloudsqlInstanceClasses
category: Database
overviewShort: "A CloudsqlInstanceClass is a non-portable resource class. It defines the desired spec of resource claims that use it to dynamically provision a managed resource."
overview: |
 "A CloudsqlInstanceClass is a non-portable resource class. It defines the desired spec of resource claims that use it to dynamically provision a managed resource."
readme: |
 Full documentation can be found in the Crossplane [API Reference docs](https://doc.crds.dev/github.com/crossplane/provider-nop/database.gcp.crossplane.io_cloudsqlinstanceclasses.yaml).
